"""add user, role, token fields

Revision ID: 6a2723545b7b
Revises: 8c690f2d0f60
Create Date: 2026-04-20 20:18:54.968005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2723545b7b'
down_revision: Union[str, Sequence[str], None] = '8c690f2d0f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', sa.String(), nullable=False))
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('tokens', sa.Column('token', sa.String(), nullable=False))
    op.add_column('tokens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tokens', sa.Column('is_revoked', sa.Boolean(), nullable=True))
    op.add_column('tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.add_column('tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tokens_token'), 'tokens', ['token'], unique=True)
    op.create_foreign_key(None, 'tokens', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_index(op.f('ix_tokens_token'), table_name='tokens')
    op.drop_column('tokens', 'created_at')
    op.drop_column('tokens', 'expires_at')
    op.drop_column('tokens', 'is_revoked')
    op.drop_column('tokens', 'user_id')
    op.drop_column('tokens', 'token')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###
